FROM quay.io/fedora/fedora 


COPY extra-packages /

#RUN dnf clean all
#RUN dnf update -y

RUN  dnf -y install $(<extra-packages) && \
	dnf -y upgrade && \
    dnf clean all

#RUN    cat /extra-packages | xargs dnf in -y -C

RUN rm /extra-packages

RUN   ln -fs /bin/sh /usr/bin/sh && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
      ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/transactional-update

CMD /usr/bin/fish

LABEL Description=mylabel
