


= What is and isn't Yogācāra
Yogācāra Buddhism Research Association Top Page 
Dan Lusthaus
:docURL: http://www.acmuller.net/yogacara/articles/intro.html
:sectnums:  
:toc:  
:stylesdir: ./styles

Yogācāra is one of the two schools of Indian Mahāyāna Buddhism. Its founding is ascribed to two half brothers, Asaṅga and Vasubandhu, but its basic tenets and doctrines were already in circulation for at least a century before the brothers lived. Yogācāra focused on the processes involved in cognition in order to overcome the ignorance that prevents one from attaining liberation from the karmic rounds of birth and death. Yogācārins' sustained attention to issues such as cognition, consciousness, perception, and epistemology, coupled with claims such as "external objects do not exist," has led some to misinterpret Yogācāra as a form of metaphysical idealism. They did not focus on consciousness to assert it as ultimately real (Yogācāra claims consciousness is only conventionally real since it arises from moment to moment due to fluctuating causes and conditions), but rather because it is the cause of the karmic problem they are seeking to eliminate.

Yogācāra introduced several important new doctrines to Buddhism, including vijñapti-mātra (nothing but cognition), three self-natures, three turnings of the Dharma-wheel, and a system of eight consciousness (all explained below). Their close scrutiny of cognition spawned two important developments: an elaborate psychological therapeutic system that mapped out the problems in cognition along with the antidotes to correct them, and an earnest epistemological endeavor that led to some of the most sophisticated work on perception and logic ever engaged in by Buddhists or Indians.

== Historical Overview

[width="15%"]
|=======
|1 |2 |A
|3 |4 |B
|5 |6 |C
|=======

Though the founding of Yogācāra is traditionally ascribed to two half-brothers, Asaṅga and Vasubandhu (fourth-fifth century C.E.), most of its fundamental doctrines had already appeared in a number of scriptures a century or more earlier, most notably the _Saṅdhinirmocana Sūtra_ (Elucidating the Hidden Connections). Among the key Yogācāra concepts introduced in the Saṅdhinirmocana Sūtra are the notions of "only-cognition" (vijñapti-mātra), three self-natures (trisvabhāva), the ālaya-vijñāna (warehouse consciousness), overturning the basis (āśraya-parāvṛtti), and the theory of eight consciousnesses.

The Saṅdhinirmocana Sūtra proclaimed its teachings to be the third turning of the wheel of Dharma. Buddha lived ca. the fifth century BCE, but Mahāyāna Sūtras did not begin to appear until roughly five hundred years later. New Mahāyāna Sūtras continued to be composed for many centuries. Indian Mahāyānists treated these Sūtras as documents that recorded actual discourses of the Buddha. By the third or fourth century CE a wide and sometimes incommensurate range of Buddhist doctrines had emerged, but whichever doctrines appeared in Sūtras could be ascribed to the authority of Buddha himself.

According to the earliest Pāli Suttas, when Buddha became enlightened he turned the wheel of Dharma, i.e., he began to teach the path to enlightenment, the Dharma (Pāli: Dhamma). While Buddhists had always maintained that Buddha had geared specific teachings to the specific capacities of specific audiences, the Saṅdhinirmocana Sūtra established the idea that Buddha had taught significantly different doctrines to different audiences based on their levels of understanding; and that these different doctrines led from provisional antidotes (pratipakṣa) for certain wrong views up to a comprehensive teaching that finally made explicit what was only implicit in the earlier teachings. In its view, the first two turnings of the wheel-the teachings of the Four Noble Truths in Nikāya and Abhidharma Buddhism, and the teachings of the Madhyamaka school, respectively-had expressed the Dharma through incomplete formulations that required further elucidation (neyārtha) in order to be properly understood and thus effective. The first turning, by emphasizing entities (dharmas, aggregates, etc.) while "hiding" emptiness, might lead one to hold a substantialistic view; the second turning, by emphasizing negation while "hiding" the positive qualities of the Dharma, might be misconstrued as nihilism. The third turning was a middle way between these extremes that finally made everything explicit (nītārtha). In order to leave nothing hidden, the Yogācārins embarked on a massive, systematic synthesis of all the Buddhist teachings that had preceded them, scrutinizing and evaluating them down to the most trivial details in an attempt to formulate the definitive (nitārtha) Buddhist teaching. Stated another way, to be effective all of Buddhism required a Yogācārin reinterpretation. Innovations in abhidharma analysis, logic, cosmology, meditation methods, psychology, philosophy, and ethics are among their most important contributions.
Asaṅga's magnum opus, the _Yogācārabhūmi-śāstra_ (Treatise on the Stages of Yoga Practice), is a comprehensive encyclopedia of Buddhist terms and models (which draws heavily on the Āgamas - the Sanskrit counterpart of the Pāli Nikāyas), mapped out according to his Yogācārin view of how one progresses along the stages of the path to enlightenment. Vasubandhu's pre-Yogācārin magnum opus, the Abhidharmakośa (Treasury of Abhidharma) also provides a comprehensive, detailed overview of the Buddhist path with meticuluous attention to nuances and differences of opinion on a broad range of exacting topics.

Though both half brothers were born Brahmins, Asaṅga is believed to have early on joined the Mahīśasikas, a non-Mahāyāna school of Buddhism deeply steeped in the Āgamas. Asaṅga and Vasubandhu became the first identifiable Yogācārins, each having initially been devoted to other schools of Buddhism. Both were prolific authors, though Asaṅga attributed a portion of his writings to Maitreya, the Future Buddha living in Tuṣita Heaven. Some modern scholars have argued that this Maitreya was an actual human teacher, not the Future Buddha, but the tradition is fairly clear. After twelve years of fruitless meditation alone in a cave (or forest, according to other versions), during a moment of utter despair when Asaṅga was ready to quit due to his abject failure, Maitreya appeared to him and transported him to Tuṣita Heaven where he instructed him in previously unknown texts, Yogācārin works, that Asaṅga then introduced to his fellow Buddhists. Precisely which texts these are is less clear, since the Chinese and Tibetan traditions assign different works to Maitreya.

According to tradition, Vasubandhu first studied Vaibhāṣika Buddhist teachings, writing an encyclopedic summary of their teachings that has become a standard work throughout the Buddhist world, the Abhidharmakośa (Treasury of Abhidharma). As he grew critical of Vaibhāṣika teachings, he wrote a commentary to that work refuting many of its tenets. Intellectually restless for a while, Vasubandhu composed a variety of works that chart his journey to Yogācāra, the best known of these being the Karmasiddhi-prakaraṇa (Investigation Establishing Karma) and Pañcaskandhaka-prakaraṇa (Investigation into the Five Aggregates). These works show a deep familiarity with the Abhidharmic categories discussed in the Kośa, with attempts to rethink them; the philosophical and scholastic disputes of the day are also explored, and the new positions Vasubandhu formulates in these texts bring him closer to Yogācārin conclusions. A few modern scholars have argued, on the basis of some conflicting accounts in old biographies of Vasubandhu, that these texts along with the Abhidharmakośa were not written by the Yogācārin Vasubandhu, but by someone else. Since the progression and development of his thought, however, is so strikingly evident in these works, and the similarity of vocabulary and style of argument so apparent across the texts, the theory of Two Vasubandhus has little merit.

The writings of Asaṅga (and/or Maitreya) and Vasubandhu ranged from vast encyclopedic compendiums of Buddhist doctrine (e.g., Yogācārabhūmi-śāstra, Mahāyānasaṃgraha, Abhidharmasamuccaya), to terse versified encapsulations of Yogācāra praxis (e.g., Triṃśikā, Trisvabhāva-nirdeśa), to focused systematic treatises on Yogācāra themes (e.g., Viṃśatika, Madhyānta-vibhāga), to commentaries on well-known Mahāyānic scriptures and treatises such as the Lotus and Diamond Sutras.

Since the Saṅdhinirmocana Sūtra offers highly sophisticated, well-developed doctrines, it is reasonable to assume that these ideas had been under development for some time, possibly centuries, before this scripture emerged. Since Asaṅga and Vasubandhu lived a century or more after the Saṅdhinirmocana appeared, it is also reasonable to assume that these ideas had been further refined by others in the interim. Thus the traditional claim that the two brothers are the founders of Yogācāra is at best a half-truth. According to tradition Asaṅga converted Vasubandhu to Yogācāra after having himself been taught by Maitreya; he is not known to have had any other notable disciples. Tradition does assign two major disciples to Vasubandhu: Dignāga, the great logician and epistemologist, and Sthiramati, an important early Yogācāra commentator. It is unclear whether either ever actually met Vasubandhu (current scholarship deems it unlikely). They may have been disciples of his thought, acquired exclusively from his writings or through some forgotten intermediary teachers. These two disciples exemplify the two major directions into which Vasubandhu's teachings split.

After Vasubandhu, Yogācāra developed into two distinct directions or wings: 1. a logico-epistemic tradition, exemplified by such thinkers as Dignāga, Dharmakīrti, śāntarakṣita, and Ratnakīrti; 2. an Abhidharmic psychology, exemplified by such thinkers as Sthiramati, Dharmapāla, Xuanzang (Hsüan-tsang), and Vinītadeva. While the first wing focused on questions of epistemology and logic, the other wing refined and elaborated the Abhidharma analysis developed by Asaṅga and Vasubandhu. These wings were not entirely separate, and many Buddhists wrote works that contributed to both wings. Dignāga, for instance, besides his works on epistemology and logic also wrote a commentary on Vasubandhu's Abhidharmakośa. What united both wings was a deep concern with the process of cognition, i.e., analyses of how we perceive and think. The former wing approached that epistemologically while the latter wing approached it psychologically and therapeutically. Both identified the root of all human problems as cognitive errors that needed correction.

Several Yogācāra notions basic to the Abhidharma wing came under severe attack by other Buddhists, especially the notion of ālaya-vijñāna, which was denounced as something akin to the Hindu notions of ātman (permanent, invariant self) and prakṛti (primordial substrative nature from which all mental, emotional and physical things evolve). Eventually the critiques became so entrenched that the Abhidharma wing atrophied. By the end of the eighth century it was eclipsed by the logico-epistemic tradition and by a hybrid school that combined basic Yogācāra doctrines with Tathāgatagarbha thought. The logico-epistemological wing in part side-stepped the critique by using the term citta-santāna, "mind-stream," instead of ālaya-vijñāna, for what amounted to roughly the same idea. It was easier to deny that a "stream" represented a reified self. On the other hand, the Tathāgatagarbha hybrid school was no stranger to the charge of smuggling notions of selfhood into its doctrines, since, for example, it explicitly defined tathāgatagarbha as "permanent, pleasurable, self, and pure (nitya, sukha, ātman, śuddha)." Many Tathāgatagarbha texts, in fact, argue for the acceptance of selfhood (ātman) as a sign of higher accomplishment. The hybrid school attempted to conflate tathāgatagarbha with the ālaya-vijñāna. Key works of the hybrid school include the Laṅkāvatāra Sūtra, Ratnagotravibhāga (Uttaratantra), and in China the Awakening of Faith.

In China during the sixth and seventh centuries, Buddhism was dominated by several competing forms of Yogācāra. A major schism between orthodox versions of Yogācāra and Tathāgatagarbha hybrid versions was finally settled in the eighth century in favor of a hybrid version, which became definitive for all subsequent forms of East Asian Buddhism. Yogācāra ideas were also studied and classified in Tibet. The Nyingma and Dzog Chen schools settled on a hybrid version similar to the Chinese Tathāgatagarbha hybrid; the Gelugpas subdivided Yogācāra into a number of different types and considered them preparatory teachings for studying Prāsaṅgika Madhyamaka, which Gelugpas rank as the highest Buddhist teaching. The Tibetans, however, tended to view the logico-epistemological tradition as distinct from Yogācāra proper, frequently labeling that Sautrāntika instead.

== Yogācāra is not Metaphysical Idealism

The school was called Yogācāra (Yoga practice) because it provided a comprehensive, therapeutic framework for engaging in the practices that lead to the goal of the bodhisattva path, namely enlightened cognition. Meditation served as the laboratory in which one could study how the mind operated. Yogācāra focused on the question of consciousness from a variety of approaches, including meditation, psychological analysis, epistemology (how we know what we know, how perception operates, what validates knowledge), scholastic categorization, and karmic analysis.
Yogācāra doctrine is summarized in the term vijñapti-mātra, "nothing-but-cognition" (often rendered "consciousness-only" or "mind-only") which has sometimes been interpreted as indicating a type of metaphysical idealism, i.e., the claim that mind alone is real and that everything else is created by mind. However, the Yogācārin writings themselves argue something very different. Consciousness (vijñāna) is not the ultimate reality or solution, but rather the root problem. This problem emerges in ordinary mental operations, and it can only be solved by bringing those operations to an end.
Yogācāra tends to be misinterpreted as a form of metaphysical idealism primarily because its teachings are taken for ontological propositions rather than as epistemological warnings about karmic problems. The Yogācāra focus on cognition and consciousness grew out of its analysis of karma, and not for the sake of metaphysical speculation. Two things should be clarified in order to explain why Yogācāra is not metaphysical idealism: 1. The meaning of the word "idealism"; and 2. an important difference between the way Indian and Western philosophers do philosophy.

=== Term 'Idealism'

The term "Idealism" came into vogue roughly during the time of Kant (though it was used earlier by others, such as Leibniz) to label one of two trends that had emerged in reaction to Cartesian philosophy. Descartes had argued that there were two basic yet separate substances in the universe: Extension (the material world of things in space) and Thought (the world of mind and ideas). Subsequently opposing camps took one or the other substance as their metaphysical foundation, treating it as the primary substance while reducing the remaining substance to derivative status. Materialists argued that only matter was ultimately real, so that thought and consciousness derived from physical entities (chemistry, brain states, etc.). Idealists countered that the mind and its ideas were ultimately real, and that the physical world derived from mind (e.g., the mind of God, Berkeley's esse est percipi, or from ideal prototypes, etc.). Materialists gravitated toward mechanical, physical explanations for why and how things existed, while Idealists tended to look for purposes - moral as well as rational - to explain existence. Idealism meant "idea-ism," frequently in the sense Plato's notion of "ideas" (eidos) was understood at the time, namely ideal types that transcended the physical, sensory world and provided the form (eidos) that gave matter meaning and purpose. As materialism, buttressed by advances in materialistic science, gained wider acceptance, those inclined toward spiritual and theological aims turned increasingly toward idealism as a countermeasure. Before long there were many types of materialism and idealism.
Idealism, in its broadest sense, came to encompass everything that was not materialism, which included so many different types of positions that the term lost any hope of univocality. Most forms of theistic and theological thought were, by this definition, types of idealism, even if they accepted matter as real, since they also asserted something as more real than matter, either as the creator of matter (in monotheism) or as the reality behind matter (in pantheism). Extreme empiricists who only accepted their own experience and sensations as real were also idealists. Thus the term "idealism" united monotheists, pantheists and atheists. At one extreme were various forms of metaphysical idealism which posited a mind (or minds) as the only ultimate reality. The physical world was either an unreal illusion or not as real as the mind that created it. To avoid solipsism (which is a subjectivized version of metaphysical idealism) metaphysical idealists posited an overarching mind that envisions and creates the universe.
A more limited type of idealism is epistemological idealism, which argues that since knowledge of the world only exists in the mental realm, we cannot know actual physical objects as they truly are, but only as they appear in our mental representations of them. Epistemological idealists could be ontological materialists, accepting that matter exists substantially; they could even accept that mental states derived at least in part from material processes. What they denied was that matter could be known in itself directly, without the mediation of mental representations. Though unknowable in itself, matter's existence and properties could be known through inference based on certain consistencies in the way material things are represented in perception.
Transcendental idealism contends that not only matter but also the self remains transcendental in an act of cognition. Kant and Husserl, who were both transcendental idealists, defined "transcendental" as "that which constitutes experience but is not itself given in experience." A mundane example would be the eye, which is the condition for seeing even though the eye does not see itself. By applying vision and drawing inferences from it, one can come to know the role eyes play in seeing, even though one never sees one's own eyes. Similarly, things in themselves and the transcendental self could be known if the proper methods were applied for uncovering the conditions that constitute experience, even though such conditions do not themselves appear in experience. Even here, where epistemological issues are at the forefront, it is actually ontological concerns, viz. the ontological status of self and objects, that is really at stake. Western philosophy rarely escapes that ontological tilt. Those who accepted that both the self and its objects were unknowable except through reason, and that such reason(s) was their cause and purpose for existing - thus epistemologically and ontologically grounding everything in the mind and its ideas - were labeled Absolute Idealists (e.g., Schelling, Hegel, Bradley), since only such ideas are absolute while all else is relative to them.
With the exception of some epistemological idealists, what unites all the positions enumerated above, including the materialists, is that these positions are ontological. They are concerned with the ontological status of the objects of sense and thought, as well as the ontological nature of the self who knows. Mainstream Western philosophy since Plato and Aristotle has treated ontology and metaphysics as the ultimate philosophic pursuit, with epistemology's role being little more than to provide access and justification for one's ontological pursuits and commitments. Since many of what are decried as philosophy's excesses - such as skepticism, solipsism, sophistry - could be and were accused of deriving from overactive epistemological questioning, epistemology has often been held suspect, and in some theological formulations, considered entirely dispensable in favor of faith. Ontology is primary, and epistemology is either secondary or expendable.

=== Differences between Indian and Western approaches to Philosophy

In Indian philosophy one finds the reverse of this. Epistemology (pramāṇavāda) is primary, both in the sense that it must be engaged in prior to attempting any other philosophical endeavor, and that the limits of one's metaphysical claims are always inviolably set by the parameters established by one's epistemology. Before one can make claims, one must establish the basis on which such claims can be proven and justified. The Indians went so far as to concede that if one wishes to debate an opponent with a differing view, one must first find a common epistemological ground upon which to argue. Failing that, no meaningful debate can transpire.
Since one's ontology (prameya) depends on what one's epistemology makes allowable, many Indian schools tried to include things in their list of valid means of knowledge (pramāṇa) that would facilitate their claims. Hindus, for instance, considered their Scriptures to be valid means of knowledge, but other Indians, such as Buddhists and Jains, rejected the authority of the Hindu Scriptures. Therefore if a Hindu debated a Buddhist or Jain, he could not appeal to the authority of Hindu Scriptures, but had to find a common epistemological ground. In the case of Buddhism that would be perception and inference; in the case of Jainism, only inference. All schools except Jains accepted perception as a valid means of knowledge, meaning that sensory knowledge is valid (if qualified as non-erroneous, non-hallucinatory, etc.). What is not presently observed but is in principle observable can be known by inference. Without actually seeing the fire, one knows it must exist on a hill when one sees smoke in that location, because both fire and smoke are in principle observable entities, and an observed necessary relation (vyāpti) exists between smoke and fire, viz. where there is smoke there is fire. Were one proximate to the fire on the hill, one would undoubtedly see the fire. One cannot make valid inferences about things impossible to perceive, such as unicorns, since no observable necessary relation obtains, so one cannot infer that a unicorn is on the hill. Perceptibility therefore is an indispensable component of both perception and inference, and thus, for Buddhists, of all valid knowledge. In order to be considered "real" (dravya) by the standards of Buddhist logic, a thing must produce an observable effect. Buddhists argued among themselves whether something was real only while it was producing this observable effect (Sautrāntika position), or whether something could be considered real if it produced an observable effect at some moment during its existence (Sarvāstivāda position), but all agreed that a thing must have observable causal efficacy (kāraṇa) in order to be considered real. This helps explain the centrality of perception and consciousness for Yogācāra theory.
The logico-epistemological wing of Yogācāra drew a sharp distinction between perception and inference. Perception involves sensory cognitions of unique, momentary, discrete particulars. Inference involves linguistic, conceptual universals, since words are meaningful and communicative only to the extent they designate and participate in universal classes commonly shared and understood by users of the language. Inferences are true or false depending on how accurately or erroneously they approximate sensory particulars, but even when linguistically true, they are still true only relative (saṃvṛti) to the sensations they approximate. Conversely, sensation (and only sensation) is beyond language. Sensory cognition devoid of linguistic overlay or theoretic assertions (samāropa) is correct cognition and precisely, not approximately, true (paramārtha). While this seems to involve metaphysical claims about categories such as particulars and universals, sensation and language, in fact it is a request that we should cognize things as they are without imposing any metaphysical assertions or conceptual framework whatsoever. The cognitive and epistemic, not the metaphysical, is at stake. What is the case is beyond description not because it is something ineffable residing outside or behind human experience, but because it is the very sensory stuff of human experience whose momentary unique actuality cannot be reduced to universalistic, eternalistic language or concepts. To interpret this position itself as a metaphysics of particularity is to remain trapped in a conceptual framework and hence to miss its point.
Epistemological concerns pervade Indian philosophy. This is especially true of Buddhist philosophy. Many Buddhist texts assert that higher understanding has nothing to do with ontology, that focusing on the existence or nonexistence of something (asti-nāsti, bhāvābhāva) is a misleading category error. They typically remove important items - such as emptiness and nirvana - from ontological consideration by explicitly declaring that these have nothing whatsoever to do with existence or nonexistence, or being and nonbeing, and they further warn that this is not a license to imagine a higher sense of existence or being into which such items are then subsumed or sublated. The Buddhist goal is not the construction of a more perfect ontology. Instead its primary target is always the removal of ignorance. Hence while Buddhists frequently suspend ontological and metaphysical speculation (tarka), denouncing it as useless or dangerous, correct cognition (samyag-jñāna) is invariably lauded. Even Madhyamakas, who question the feasibility of much of Buddhist epistemology, insist that we should understand where the errors lie and correct the way we cognize accordingly. Stated bluntly, Buddhism is concerned with Seeing, not Being; i.e., epistemology rather than ontology.
Tellingly no Indian Yogācāra text ever claims that the world is created by mind. What they do claim is that we mistake our projected interpretations of the world for the world itself, i.e., we take our own mental constructions to be the world. Their vocabulary for this is as rich as their analysis: kalpanā (projective conceptual construction), parikalpa and parikalpita (ubiquitous imaginary constructions), abhūta-parikalpa (imagining something in a locus in which it does not exist), prapañca (proliferation of conceptual constructions), to mention a few. Correct cognition is defined as the removal of those obstacles which prevent us from seeing dependent causal conditions in the manner they actually become (yathā-bhūtam). For Yogācāra these causal conditions are cognitive, not metaphysical; they are the mental and perceptual conditions by which sensations and thoughts occur, not the metaphysical machinations of a Creator or an imperceptible domain. What is known through correct cognition is euphemistically called tathatā, "suchness," which the texts are quick to point out is not an actual thing, but only a word (prajñapti-mātra).

=== Yogācāra Philosophical Approach

What is crucial in the forgoing for understanding Yogācāra is that its attention to perceptual and cognitive issues is in line with basic Buddhist thinking, and that this attention is epistemological rather than metaphysical. When Yogācārins discuss "objects," they are talking about cognitive objects, not metaphysical entities. Cognitive objects (viṣaya) are real, integral parts of cognition, and thus occur within acts of consciousness. While confirming viṣaya as integral to cognitive acts, they deny that any artha (that toward which an intentionality intends, i.e., an object of intentionality) exists outside the cognitive act in which it is that which is intended. Intentional objects only appear in acts of intentionality, i.e., consciousness. In other words, Yogacarins don't claim that nothing whatsoever exists outside the mind. First of all, there is no overarching mind for Yogācāra; each individual mind is distinct. Yogacarins are not monadologists in the Leibnitzian mold. Second, artha does not signify a mere neutral 'object;' but rather a telos toward which an act of consciousness intends. This focus of intent -- intent being a form of desire -- is integral to consciousness, and, as a focus, never occurs anywhere other than in such an act of consciousness. For Yogācāra viṣaya (cognitive object) and artha (intentional object) exist, but only in the acts of consciousness within which they are constituted as cognitive and intentional. It is important to keep in mind that for Yogācāra an act of consciousness is as much constituted by intentionality and cognitive factors as vice versa. Consciousness enjoys no transcendent status, nor does it serve as a metaphysical foundation. Consciousness is real by virtue of its facticity -- the fact that sentient beings experience cognitions -- and not because of an ontological primacy.
Rather than offer up one more ontology, Yogacarins attempt to uncover and eliminate the predilections and proclivities (āśrava, anuśaya) that compel people to generate and cling to such theoretical ontological constructions. Since, according to Yogācāra, all ontologies are epistemological constructions, to understand how cognition operates is to understand how and why people construct the ontologies to which they cling. Ontological attachment is a symptom of cognitive projection (pratibimba, parikalpita). Careful examination of Yogācāra texts reveals that they make no ontological claims, except to question the validity of making ontological claims. The reason they give for their ontological silence is that were they to offer a metaphysical description, that description would be appropriated by its interpreters who, due to their proclivities, would project onto it what they wish reality to be, thereby reducing the description to their own presupposed theory of reality. Such projective reductionism is the problem and symptomatic of the most basic proclivities afflicting sentient beings. That is what vijñapti-mātra means, viz., to mistake one's projections for that onto which one is projecting. Vasubandhu's Thirty Verses (Triṃśikā) states that if one clings to one's projection of the idea of vijñapti-mātra, then one fails to truly dwell in the understanding of vijñapti-mātra (verse 27). Enlightened cognition free of all cognitive errors is defined as nirvikalpa-jñāna, "cognition without imaginative construction," i.e., without conceptual overlay. Ironically, Yogācāra's interpreters and opponents nevertheless could not resist reductively projecting metaphysical theories onto what Yogācārins did say, at once proving Yogācāra was right and at the same time making actual Yogācāra teachings that much harder to access. Interpreting their epistemological analyses as metaphysical pronouncements fundamentally misconstrues their project.
The arguments Yogācāra deploys frequently resemble those made by epistemological idealists. Recognizing those affinities Western scholars early in the twentieth century compared Yogācāra to Kant, and more recently scholars have begun to think that Husserl's phenomenology comes even closer. There are indeed intriguing similarities, for instance between Husserl's description of noesis (consciousness projecting its cognitive field) and noema (the constructed cognitive object) on the one hand, and Yogācāra's analysis of the (cognitive) grasper and the grasped (grāhaka and grāhya) on the other hand. But there are also important differences between those Western philosophers and Yogācāra. The three most important are:

. Kant and Husserl play down notions of causality, while Yogācāra developed complex systematic causal theories it deemed to be of the greatest importance;
. there is no counterpart to either karma or enlightenment in the Western theories, while these are the very raison d'être for all Yogācāra theory and practice;
. finally, the Western philosophies are designed to afford the best possible access to an ontological realm (at least sufficient to acknowledge its existence), while Yogācāra is critical of that motive in all its manifestations.
To the extent that epistemological idealists can also be critical realists, Yogācāra may be deemed a type of epistemological idealism, with the proviso that the purpose of its arguments was not to engender an improved ontological theory or commitment, but rather an insistence that we pay the fullest attention to the epistemological and psychological conditions compelling us to construct and attach to ontological theories.

== Karma, Matter, and Cognitive Appropriation

The key to Yogācāra theory lies in the Buddhist notions of karma which they inherited and rigorously reinterpreted. As earlier Buddhist texts already explained, karma is responsible for suffering and ignorance, and karma consists of any intentional activity of body, language, or mind. Since the crucial factor is intent, and intent is a cognitive condition, whatever lacks cognition is both non-karmic and non-intentional. Hence, by definition, whatever is non-cognitive can have no karmic influence or consequences. Since Buddhism aims at overcoming ignorance and suffering through the elimination of karmic conditioning, Buddhism, Yogacarins reasoned, is only concerned with the analysis and correction of whatever falls within the domain of cognitive conditions. Hence questions about the ultimate reality of non-cognitive things are simply irrelevant and useless for solving the problem of karma. Further, Yogācārins emphasize that categories such as materiality (rūpa) are cognitive categories. "Materiality" is a word for the colors, textures, sounds, etc., that we experience in acts of perception, and it is only to the extent that they are experienced, perceived and ideologically grasped, thereby becoming objects of attachment, that they have karmic significance. Intentional acts also have moral motives and consequences. Since effects are shaped by their causes, an act with a wholesome intent would tend to yield wholesome fruits, while unwholesome intentions produce unwholesome effects.
In contrast to the cognitive karmic dimension, Buddhism considered material elements (rūpa) karmically neutral. The problem with material things is not their materiality, but the psychology of appropriation (upādāna) - desiring, grasping, clinging, attachment - that infests our ideas and perceptions of such things. It is not the materiality of gold that leads to problems, but rather our ideas about the value of gold and the attitudes and actions we engage in as a result of those ideas. Those ideas were acquired through previous experiences. By repeated exposure to certain ideas and cognitive conditions, one is conditioned to respond habitually in a similar manner to similar circumstances. Eventually these habits are embodied, becoming reflexive, presuppositional. For Buddhists this process by which conditioning becoming embodied (saṃskāra) is not confined to a single life-time, but accrues over many life-times. Saṃsāra (the continuous cycle of birth and death) is the karmic en-act-ment of this repetition, the reoccurrence of cognitive embodied habits in new life situations and life forms.
For all Buddhists this follows a simple sensory calculus: Pleasurable feelings we wish to hold on to, or repeat. Painful feelings we wish to cut off, or avoid. Pleasure and pain, reward and punishment, approval and disapproval, and so on, condition us. Our karmic habits (vāsanā) are constructed this way. Since all is impermanent, pleasurable feelings cannot be maintained or repeated permanently; painful things (such as sickness and death) cannot be avoided permanently. The greater the dissonance between our actual impermanent experience and our expectations for permanent desired ends, the more we suffer, and the greater tendency (anuśaya) toward projecting our desires onto the world as compensation. Though nothing whatsoever is permanent, we imagine all sort of permanent things - from God to soul to essences - in an effort to avoid facing the fact that none of us has a permanent self. We think that if we can prove something is permanent, anything, then we too have a chance for permanence. The anxiety about our lack of self and all the cognitive and karmic mischief that anxiety generates is called several things by Yogācāra, including jñeyāvaraṇa (obstruction of the knowable, i.e., our self-obsessions prevent us from seeing things as they are) and abhūta-parikalpa (imagining something - namely permanence or a self - to exist in a locus in which it is absent).
Previous Buddhists - most notably the Sautrāntikas, but also the Abhidharma schools - had developed a sophisticated metaphoric vocabulary to describe and analyze the causes and conditions of karma in terms of seeds (bījā). Just as a plant develops from its roots unseen underground, so do previous karmic experiences fester unseen in the mind; just as a plant sprouts from the ground when nourished by proper conditions, so do karmic habits, under the right causes and conditions, reassert themselves as new experiences; just as plants reach fruition by producing new seeds that re-enter the ground to take root and begin regrowing a similar plant of the same kind, so do karmic actions produce wholesome or unwholesome fruit that become latent seeds for a later, similar type of action or cognition. Just as plants reproduce only their own kind, so do wholesome or unwholesome karmic acts produce effects after their own kind. This cycle served as a metaphor for the process of cognitive conditioning as well as the recurrent cycle of birth and death (saṃsāra). Since Yogācāra accepts the Buddhist doctrine of momentariness, seeds are said to perdure for only a moment during which they become the cause of a similar seed that succeeds them. Momentary seeds are causally linked in sequential chains, each momentary seed a link in a chain of karmic causes and effects.
Seeds are basically divided into two types: wholesome and unwholesome. Unwholesome seeds are the acquired cognitive habits preventing one from reaching enlightenment. Wholesome seeds - also labeled "pure" and "unpolluted" - give rise to more pure seeds, which bring one closer to enlightenment. In general Yogācāra differentiates inner seeds (personal conditioning) from external seeds (being conditioned by others). One's own seeds can be modified or affected by exposure to external conditions (external seeds), which can be beneficial or detrimental. Exposure to polluting conditions intensifies one's unwholesome seeds, while contact with "pure" conditions, such as hearing the Correct Teaching (Saddharma), can stimulate one's wholesome seeds to increase, thereby diminishing and ultimately eradicating one's unwholesome seeds.
Another metaphor for karmic conditioning that accompanies the seed metaphor is "perfuming" (vāsanā). A cloth exposed to the smell of perfume acquires its scent. Similarly one is mentally and behaviorally conditioned by what one experiences. This conditioning produces karmic habits, but just as the odor can be removed from the cloth so can one's conditioning be purified of perfumed habits. Typically three types of perfuming are discussed: 1. linguistic and conceptual habits; 2. habits of self-interest and "grasping self" (ātma-grāha), i.e., the belief in self and what belongs to self; and 3. Habits leading to subsequent life situations (bhāvāṅga-vāsanā), i.e., the long-term karmic consequences of specific karmic activities.
Yogācāra literature debates the relation between seeds and perfuming. Some claim that seeds and perfuming are really two terms for the same thing, viz. acquired karmic habits. Others claim that seeds are simply the effects of perfuming, i.e., all conditioning is acquired through experience. Still others contend that "seed" refers to the chains of conditioned habits one already has (whether acquired in this life, in some previous life, or even "beginninglessly") while "perfuming" denotes the experiences one has that modify or affect the development of one's seeds. "Beginningless" might be understood as a corollary to Husserl's term "transcendental," i.e., a causal sequence constituting a present experience whose own original cause remains undisclosed in this experience. Some claimed that one's possibilities for enlightenment depended entirely on the sort of seeds one already possessed; perfuming merely acted as a catalyst but could not provide wholesome seeds if one did not already possess them. Beings utterly devoid of wholesome seeds were called icchantikas (incorrigibles); such beings could never reach enlightenment. Some other Mahāyāna Buddhists, feeling that this violated the Mahāyāna dictum of universal salvation, attacked the incorrigibility doctrine.
The karmic cause of the fundamental dis-ease (duḥkha) is desire expressed through body, speech, or mind. Therefore Yogācāra focused exclusively on cognitive and mental activities in relation to their intentions, i.e., the operations of consciousness, since the problem was located there. Buddhism had always identified ignorance and desire as the primary causes of suffering and rebirth. Yogācārins mapped these mental functions in order to dismantle them. Because maps of this sort were also creations of the mind, they too would ultimately have to be abandoned in the course of the dismantling, but their therapeutic value would have been served in bringing about enlightenment. This view of the provisional expediency of Buddhism can be traced back to Buddha himself. Yogācārins describe enlightenment as resulting from Overturning the Cognitive Basis (āśraya-paravṛtti), i.e., overturning the conceptual projections and imaginings which act as the base of our cognitive actions. This overturning transforms the basic mode of cognition from consciousness (vi-jñāna, dis-cernment) into jñāna (direct knowing). The vi- prefix is equivalent to dis- in English - dis-criminate, dis-tinguish, dis-engage, dis-connect - meaning to bifurcate or separate from. Direct knowing was defined as non-conceptual (nirvikalpa-jñāna), i.e., devoid of interpretive overlay. 
The case of material elements is important for understanding one reason why Yogācāra is not metaphysical idealism. No Yogācāra text denies materiality (rūpa) as a valid Buddhist category. On the contrary, Yogācārins include materiality in their analysis. Their approach to materiality is well rooted in Buddhist precedents. Frequently Buddhist texts substitute the term "sensory contact" (Pāli: phassa, Sanskrit: sparśa) for the term "materiality." This substitution is a reminder that physical forms are sensory, that they are known to be what they are through sensation. Even the earliest Buddhist texts explain that the four primary material elements (mahābhūta) are the sensory qualities solidity, fluidity, temperature, and mobility; their characterization as earth, water, fire, and air, respectively, is declared an abstraction. Instead of concentrating on the fact of material existence, one observes how a physical thing is sensed, felt, perceived. Yogācāra never denies that there are sense-objects (viṣaya, artha, ālambana, etc.), but it denies that it makes any sense to speak of cognitive objects occurring outside an act of cognition. Imagining such an occurrence is itself a cognitive act. Yogācāra is interested in why we feel compelled to so imagine.
Everything we know, conceive, imagine, or are aware of, we know through cognition, including the notion that entities might exist independent of our cognition. The mind doesn't create the physical world, but it produces the interpretative categories through which we know and classify the physical world, and it does this so seamlessly that we mistake our interpretations for the world itself. Those interpretations, which are projections of our desires and anxieties, become obstructions (āvaraṇa) preventing us from seeing what is actually the case. In simple terms we are blinded by our own self-interests, our own prejudices (which means what is already prejudged), our desires. Unenlightened cognition is an appropriative act. Yogācāra does not speak about subjects and objects; instead it analyzes perception in terms of graspers (grāhaka) and what is grasped (grāhya).
Yogācāra at times resembles epistemological idealism, which does not claim that this or any world is constructed by mind, but rather that we are usually incapable of distinguishing our mental constructions and interpretations of the world from the world itself. This narcissism of consciousness Yogācāra calls vijñapti-mātra, [mysmall]#nothing butxx conscious construction# A deceptive trick is built into the way consciousness operates at every moment. Consciousness projects and constructs a cognitive object in such a way that it disowns its own creation - pretending the object is "out there" - in order to render that object capable of being appropriated. Even while what we cognize is occurring within our act of cognition, we cognize it as if it were external to our consciousness. Realization of vijñapti-mātra exposes this trick intrinsic to consciousness's workings, thereby eliminating it. When that deception is removed one's mode of cognition is no longer termed vijñāna (consciousness); it has become direct cognition (jñāna) (see above). Consciousness engages in this deceptive game of projection, dissociation, and appropriation because there is no "self." According to Buddhism, the deepest, most pernicious erroneous view held by sentient beings is the view that a permanent, eternal, immutable, independent self exists. There is no such self, and deep down we know that. This makes us anxious, since it entails that no self or identity endures forever. In order to assuage that anxiety, we attempt to construct a self, to fill the anxious void, to do something enduring. The projection of cognitive objects for appropriation is consciousness's main tool for this construction. If I own things (ideas, theories, identities, material objects), then "I am." If there are eternal objects that I can possess, then I too must be eternal. To undermine this desperate and erroneous appropriative grasping, Yogācāra texts say: Negate the object, and the self is also negated (e.g., Madhyānta-vibhāga, 1:4, 8).

Yogācārins deny the existence of external objects in two senses.

. In terms of conventional experience they do not deny objects such as chairs, colors, and trees, but rather they reject the claim that such things appear anywhere else than in consciousness. It is externality, not objects per se, that they challenge.

. While such objects are admissible as conventionalisms, in more precise terms there are no chairs, trees, etc. These are merely words and concepts by which we gather and interpret discrete sensations that arise moment by moment in a causal flux. These words and concepts are mental projections.
The point is not to elevate consciousness, but to warn us not to be fooled by our own cognitive narcissism. Enlightened cognition is likened to a great mirror that impartially and fully reflects everything before it, without attachment to what has passed nor in expectation of what might arrive. What sorts of objects do enlightened ones cognize? Yogācārins refuse to provide an answer aside from saying it is purified from karmic pollution (anāśrava), since whatever description they might offer would only be appropriated and reduced to the habitual cognitive categories that are already preventing us from seeing properly.

== Eight Consciousnesses

The most famous innovation of the Yogācāra school was the doctrine of eight consciousnesses. Standard Buddhism described six consciousnesses, each produced by the contact between its specific sense organ and a corresponding sense object. When a functioning eye comes into contact with a color or shape, visual consciousness is produced. When a functioning ear comes into contact with a sound, auditory consciousness is produced. Consciousness does not create the sensory sphere, but on the contrary is an effect of the interaction of a sense organ and its proper object. If an eye does not function but an object is present, visual consciousness does not arise. The same is true if a functional eye fails to encounter a visual object. Consciousness arises dependent on sensation. There are altogether six sense organs (eye, ear, nose, mouth, body, and mind) which interact with their respective sensory object domains (visual, auditory, olfactory, gustatory, tactile, and mental spheres). Note that the mind is considered another sense since it functions like the other senses, involving the activity of a sense organ (manas), its domain (mano-dhātu), and the consciousness (mano-vijñāna) resulting from the contact of organ and object. Each domain is discrete, which means vision, audition, and each of the remaining spheres function apart from each other. Hence deaf can see, and blind can hear. Objects, too, are entirely specific to their domain, and the same is true of the consciousnesses. Visual consciousness is entirely distinct from auditory consciousness, and so on. Hence there are six distinct types of consciousness (visual, auditory, olfactory, gustatory, tactile, and mental consciousness). These eighteen components of experience - viz. six sense organs, six sense object domains, and six resulting consciousnesses - were called the eighteen dhātus. According to standard Buddhist doctrine these eighteen exhaust the full extent of everything in the universe, or more accurately, the sensorium.
Early Buddhist Abhidhamma, focusing on the mental and cognitive aspects of karma, expanded the three components of the mental level - mind (manas), mental-objects (mano-dhātu), and mental-consciousness (mano-vijñāna) - into a complex system of categories. The apperceptive vector in any cognitive moment was called citta. The objects, textures, emotional, moral, and psychological tones of citta's cognitions were called caittas. Caittas (lit.: "associated with citta") were subdivided into numerous categories that varied in different Buddhist schools. Some caittas are "universal," meaning they are components of every cognition (e.g., sensory contact, hedonic tone, attention, etc.); some are "specialized," meaning they only occur in some, not all, cognitions (e.g., resolve, mindfulness, meditative clarity, etc.). Some caittas are wholesome (e.g., faith; lack of greed, hatred, or misconception; tranquility; etc.), some unwholesome, some are mental disturbances (kleśa) (appropriational intent, aversion, arrogance, etc.) or secondary mental disturbances (anger, envy, guile, shamelessness, etc.), and some are karmically indeterminate (torpor, remorse, etc.).
As Abhidharma grew more complex, disputes intensified between different Buddhist schools along a range of issues. For Yogācāra the most important problems revolved around questions of causality and consciousness. In order to avoid the idea of a permanent self, Buddhists said citta is momentary. Since a new citta apperceives a new cognitive field each moment, the apparent continuity of mental states was explained causally by claiming each citta, in the moment it ceased, also acted as cause for the arising of its successor. This was fine for continuous perceptions and thought processes, but difficulties arose since Buddhists identified a number of situations in which no citta at all was present or operative, such as deep sleep, unconsciousness, and certain meditative conditions explicitly defined as devoid of citta (āsaṃjñī-samāpatti, nirodha-samāpatti). If a preceding citta had to be temporally contiguous with its successor, how could one explain the sudden restarting of citta after a period of time had lapsed since the prior citta ceased? Where had citta or its causes been residing in the interim? Analogous questions were: from where does consciousness reemerge after deep sleep? How does consciousness begin in a new life? The various Buddhist attempts to answer these questions led to more difficulties and disputes.
Yogācārins responded by rearranging the tripartite structure of the mental level of the eighteen dhātus into three novel types of consciousnesses. Mano-vijñāna (empirical consciousness) became the sixth consciousness (and operated as the sixth sense organ, which previously had been the role of manas), surveying the cognitive content of the five senses as well as mental objects (thoughts, ideas). Manas became the seventh consciousness, redefined as primarily obsessed with various aspects and notions of "self," and thus called "defiled manas" (kliṣṭa-manas). The eighth consciousness, ālaya-vijñāna, "warehouse consciousness," was totally novel. The Warehouse Consciousness was defined in several ways. It is the receptacle of all seeds, storing experiences as they "enter" until they are sent back out as new experiences, like a warehouse handles goods. It was also called vipāka consciousness: vipāka means the "maturing" of karmic seeds. Seeds gradually matured in the repository consciousness until karmically ripe, at which point they reassert themselves as karmic consequences. Ālaya-vijñāna was also called the "basic consciousness" (mūla-vijñāna) since it retains and deploys the karmic seeds that both influence and are influenced by the other seven consciousnesses. When, for instance, the sixth consciousness is dormant (while one sleeps, or is unconscious, etc.), its seeds reside in the eighth consciousness, and they "restart" when the conditions for their arising are present. The eighth consciousness is largely a mechanism for storing and deploying seeds of which it remains largely unaware. Cittas occur as a stream in ālaya-vijñāna, but they mostly cognize the activities of the other consciousnesses, not their own seeds. For Yogācāra 'ignorance' (avidya) in part means remaining ignorant of what is transpiring within one's own ālaya-vijñāna. In states devoid of citta, the flow of cittas are repressed, held back, but their seeds continue to regenerate without being noticed, until they reassert a new stream of cittas. Warehouse Consciousness acts as the pivotal karmic mechanism, but is itself karmically neutral. Each individual has its own Warehouse Consciousness which perdures from moment to moment and life to life, though, being nothing more than a collection of ever-changing "seeds," it is continually changing and therefore not a permanent self. There is no Universal collective mind in Yogācāra.
Enlightenment consists in bringing the eight consciousnesses to an end, replacing them with enlightened cognitive abilities (jñāna). Overturning the Basis turns the five sense consciousnesses into immediate cognitions that accomplish what needs to be done (kṛtyānuṣṭhāna-jñāna). The sixth consciousness becomes immediate cognitive mastery (pratyavekṣaṇa-jñāna), in which the general and particular characteristics of things are discerned just as they are. This discernment is considered nonconceptual (nirvikalpa-jñāna). Manas becomes the immediate cognition of equality (samatā-jñāna), equalizing self and other. When the Warehouse Consciousness finally ceases it is replaced by the Great Mirror Cognition (Mahādarśa-jñāna) that sees and reflects things just as they are, impartially, without exclusion, prejudice, anticipation, attachment, or distortion. The grasper-grasped relation has ceased. It should be noted that these "purified" cognitions all engage the world in immediate and effective ways by removing the self-bias, prejudice, and obstructions that had prevented one previously from perceiving beyond one's own narcissistic consciousness. When consciousness ends, true knowledge begins. Since enlightened cognition is nonconceptual its objects cannot be described. Thus Yogacarins provide no descriptions, much less ontological accounts, of what becomes evident in these types of enlightened cognitions, except to say they are 'pure' (of imaginative constructions).
One more Yogācāra innovation was the notion that a special type of cognition emerged and developed after enlightenment. This post-enlightenment cognition was called pṛṣṭhalabdha-jñāna, and it concerned how one who has understood things as they actually become (yathā-bhūtam) now engages the world to assist other sentient beings in overcoming suffering and ignorance.

== Three Self-natures

The Three Self-nature theory (tri-svabhāva), which is explained in many Yogācāra texts including an independent treatise by Vasubandhu devoted to the subject (Trisvabhāva-nirdeśa-śāstra), maintains that there are three "natures" or cognitive realms at play.

. The conceptually constructed realm (parikalpita-svabhāva) ubiquitously imputes unreal conceptions, especially permanent "selves," into whatever it experiences, including oneself.

. The realm of causal dependency (paratantra-svabhāva), when mixed with the constructed realm, leads one to mistake impermanent occurrences in the flux of causes and conditions for fixed, permanent entities. It can be purified of these delusions by

. the perfectional realm (pariniṣpanna-svabhāva) which, like the Madhyamaka notion of emptiness on which it is based, acts as an antidote (pratipakṣa) that "purifies" or cleans all delusional constructions out of the causal realm.
The conceptually constructed realm is the erroneous narcissistic realm in which we primarily dwell, filled with projections we have acquired and habituated and embodied. Paratantra (lit. 'dependent on other') emphasizes that everything arises causally dependent on things other than itself (i.e., everything lacks self-existence). The perfectional realm signifies the absence of svabhāva (independent, self-existent, permanent nature) in everything.
When the causally dependent realm is cleansed of all defilements it becomes "enlightened." These self-natures are also called the Three Non-self-natures, since they lack fixed, independent, true, permanent identities and thus shouldn't be hypostatized. The first is unreal by definition; the third is intrinsically "empty" of self-nature, i.e., it is the very definition of non-self-nature; and the second (which finally is the only "real" one) is of unfixed nature since it can be "mixed" with either of the other two. Understanding the purified second nature is equivalent to understanding dependent origination (pratītya-samutpāda), which all schools of Buddhism accept as Buddhism's core doctrine and which tradition claims Buddha came to realize under the Bodhi Tree on the night of his enlightenment.

== Five Stages

Yogācāra literature is so vast that one should not be surprised to find that many of its attempts to provide detailed systems run into conflict with each other. Since it was a self-critical scholastic tradition, it was not uncommon for Yogācāra texts to discuss and criticize the positions of other Yogācāra texts as well as their more obvious opponents. Yogācāra positions on the stages of the path are diverse. The Daśabhūmika-sūtra-śāstra, a commentary attributed to Vasubandhu on the Ten Stages Scripture (Daśabhūmika-sūtra), describes the progress of the Bodhisattva path to Mahāyānic liberation in ten stages, comparable to the ten stages implicit in the Mahāyānic formulation of the ten perfections of wisdom. Asaṅga's Yogācārabhūmi-śāstra describes a series of seventeen stages. There are other formulations, such as the five stage path that offers a useful overview of the other formulations. We will briefly summarize the five stage path as set out in Xuanzang's Cheng weishilun.

The first stage is called "provisioning" (sambhārāvasthā) since this is the stage at which one collects and stocks up on "provisions" for the journey. These provisions primarily consist of orienting oneself toward the pursuit of the path and developing the proper character, attitude and resolve to accomplish it. It begins the moment the aspiration for enlightenment arises (bodhicitta).

The next stage is the "experimental" stage (prayogāvasthā), in which one begins to experiment with correct Buddhist theories and practices, learning which work and which don't, which are true and which are not. One begins to suppress the grasper-grasped relation and begins to study carefully the relation between things, language, and cognition.

After honing one's discipline, one eventually enters the third stage, "deepening understanding" (prativedhāvasthā). Some texts refer to this as the Path of Corrective Vision (darśana-mārga). This stage ends once one has acquired some insight in nonconceptual cognition.

Nonconceptual cognition deepens in the next stage, the Path of Cultivation (bhāvanā-mārga). The grasper-grasped relation is utterly eliminated as are all cognitive obstructions. This path culminates in the Overturning of the Basis, or enlightenment.

In the "final stage" (niṣṭhāvasthā), one abides in Unexcelled Complete Enlightenment and engages the world through the five immediate cognitions (see above). All one's activities and cognitions at this stage are "post-realization." As a Mahāyānist, from the first stage one has been devoting oneself not only to one's own attainment of enlightenment, but to the attainment of enlightenment by all sentient beings. In this stage that becomes one's sole concern.

Bibliography

Anacker, Stefan. (1984) Seven Works of Vasubandhu. Delhi: Motilal Banarsidass (important translation and discussion of key works by Vasubandhu, including some of his pre-Yogācāra treatises)

Buswell, Robert E. (1989) The Formation of Ch'an Ideology in China and Korea: The Vajrasamādhi-Sūtra, a Buddhist Apocryphon. Princeton: Princeton University Press (the introductory essay to this book contains the most thorough published account in English of the debate between Chinese Yogācāra and Tathāgatagarbha schools. However its presentation represents the latter's viewpoint which substantially distorts actual Yogācāra positions)

Griffiths, Paul. (1986) On Being Mindless: Buddhist Meditation and the Mind-Body Problem. La Salle, IL: Open Court (Analytic philosophical discussion of the "mindless" cessation meditations, translating and examining some relevant sections of Theravāda, Vaibhāṣika, and Yogācāra texts. This book is helpful for understanding how Yogācārin positions relate to Buddhism at large)

Griffiths, Paul, Hakamaya Noriaki, John Keenan, and Paul Swanson. (1989) The Realm of Awakening: Chapter Ten of Asaṅga's Mahāyānasaṃgraha. NY and Oxford: Oxford University Press (collective effort from a class taught by Hakamaya at the University of Wisconsin. Compares and translates Chinese and Tibetan versions of the root text as well as major commentaries. A good presentation of the scholastically dense style of some Yogācāra texts)

Hayes, Richard P. (1988) Dignāga on the Interpretation of Signs. Studies of Classical India, Vol. 9. Dordrecht: Kluwer Academic Publishers (A superb and challenging examination of Buddhism's most famous logician)

Kochumuttom, Thomas. (1982) A Buddhist Doctrine of Experience. Delhi: Motilal Banarsidass (translation and critical analysis of Vasubandhu's major Yogācāra texts that argues they should be interpreted as Critical Realism rather than Idealism)

Lamotte, 'Etienne (translator). (1935) Saṃdhinirmocana-sūtra. Louvain and Paris: Universit'e de Louvain & Adrian Maisonneuve (richly annotated French translation drawing on Tibetan and Chinese versions. John Powers has published an English translation from the Tibetan - 1995, Wisdom of the Buddha: The Saṃdhinirmocana Mahāyāna Sūtra, Berkeley: Dharma Publishing)

Lusthaus, Dan. (2000) Buddhist Phenomenology: A Philosophic Investigation of Yogāacara Buddhism and the Ch'eng wei-shih lun. London: Curzon Press (An investigation of the transmission of Yogācāra philosophy from India to China)

Nagao, Gadjin. (1991) Mādhyamika and Yogācāra. translated by Leslie Kawamura. Albany: State University of New York Press (a fine collection of essays by one of Japan's leading Yogācāra scholars)

Powers, John. (1991) The Yogācāra School of Buddhism: A Bibliography. Metuchen, NJ: Scarecrow Press (A fairly comprehensive bibliography, listing virtually all known Yogācāra works in Sanskrit and Tibetan and most standard Western language works. Its coverage of East Asian Yogācāra is less complete)

Rahula, Walpola (translator). (1971) Le Compendium de la Super-Doctrine d'Asaṅga (Abhidharmasamuccaya). Paris: Publications de l''Ecole Française d'Extrême Orient (the only Western language translation of this important Asaṅga text)

Sparham, Gareth (translator). (1993) Ocean of Eloquence: Tsong kha pa's Commentary on the Yogācāra Doctrine of Mind. Albany: State University of New York Press (translation of an interesting work by the Great Tibetan Gelugpa reformer from his early days)

Tatz, Mark. (1986) Asaṅga's Chapter on Ethics with the commentary of Tsong-kha-pa. Lewiston, NY: Edwin Mellen Press (translation and discussion of the section on ethics from the Bodhisattvabhūmi chapter of the Yogācārabhūmi)

Xuanzang (Hsü;an-tsang). (659) Cheng weishilun (Treatise Establishing Vijñapti-mātra). Taishou Shinshū Daizokyou 1585.31 1-59; translated into French by Louis de la Vall'ee Poussin, (1928) Vijñaptimātratāsiddhi, Paris, 2 vols.; translated into English by Wei Tat, (1973) Ch'eng Wei-Shih Lun: The Doctrine of Mere Consciousness, Hong Kong; partial English translation by Swati Ganguly, (1992) Treatise in Thirty Verses on Mere-Consciousness, Delhi: Motilal Banarsidass (Xuanzang's seventh century Chinese work, a commentary on Vasubandhu's Triṃśikā that drew on Sanskrit commentaries, became one of the standard expositions of Yogācāra doctrine in East Asia. Vall'ee Poussin's rendering is very loose, drawing on old Japanese scholarship and Chinese commentaries. Vall'ee Poussin interprets the text Idealistically. Tat's version is an English rendition of Vall'ee Poussin's French text, minus the latter's extensive annotations. Ganguly's abridgement is convenient but frequently mistaken)

Last modified: (2018-03-17 04:23:57 UTC)
