# Prerequisites: just and fish

set shell := ["fish","-c"]
set ignore-comments

# Echo home
echo-home:
		ls ~/.local/bin

# Add directories {{{1
directories:
	if not test -d ~/.local/bin; mkdir -p ~/.local/bin; end
	if not test -d ~/.local/share; mkdir -p ~/.local/share; end
	if not test -d ~/tmp; mkdir -p ~/tmp; end

#Fedora console apps {{{1
dnf-misc:
	sudo dnf install -y micro ugrep fd-find wget duf mosh bat fzf kitty-terminfo

# Batextras
batextras:
	sudo dnf install dnf-plugins-core 
	sudo dnf copr enable awood/bat-extras
	sudo dnf install bat-extras


#Fish config and Fisher plugin manager {{{1
fish_shell:
	sudo chsh -s /usr/bin/fish andmalc
	#Fisher install to ~/.config/fish/functions
	curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
	fisher update

#Fish plugins additional
#fish_fisher_additional:
#fish-fastdir
#https://github.com/danhper/fish-fastdir
#	fisher install tuvistavie/fish-fastdir


#Nvim {{{1
nvim-nightly:
	# Pulls in 51MB of dependencies
	sudo dnf copr enable agriffis/neovim-nightly
	sudo dnf install  neovim python3-neovim

	#sudo dnf install -y neovim
	#Nvim-Plug
	sh -c "curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# Chezmoi {{{1
chezmoi-install-init:
	#Installs to local bin
	sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply git@github.com:andmalc/dotfiles.git


# Broot file browser {{{1
broot:
	sudo dnf copr enable -y petersen/broot
	sudo dnf update -y
	sudo dnf install -y broot

# Elvish shell {{{1
elvish:
	wget -O - https://dl.elv.sh/linux-386/elvish-HEAD.tar.gz | tar xzvf - -C ~/.local/bin  --show-transformed  --transform='s/-HEAD//'
	#alternative curl -s -L <URL>

# Bitwarden Appimage
bitwarden:
	#Desktop file and icon png should be in ~/.local/share/application via chezmoi
	wget -O ~/.local/bin/bitwarden.appimage https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=appimage
#Eget https://github.com/zyedidia/eget {{{1
eget:
	curl https://zyedidia.github.io/eget.sh | sh
	mv eget ~/.local/bin

#Eget installed apps {{{1

# Micro {{{2
micro:
	eget zyedidia/micro --upgrade-only --to ~/.local/bin/ 

# Zellij {{{2
zellij:
	eget --upgrade-only --to ~/.local/bin/zellij zellij-org/zellij


# vim: fdm=marker ft=make
