---
-   hosts: 127.0.0.1
    tasks:
    -   name: nova
        nova_compute:
            state: absent
            auth_url: https://region-b.geo-1.identity.hpcloudsvc.com:35357/v2.0/
            login_username: andmalc
            login_password: SV55Qv0c5fXd
            login_tenant_name: andmalc-project1
            name: jessie
            image_id: c382e6b2-e507-4f93-967e-b785f6be3379
            key_name: hpcloud
            wait_for: 200
            flavor_id: 4
            #       nics:
            #         - net-id: 34605f38-e52a-25d2-b6ec-754a13ffb723
        meta:
         hostname: jessievm
         group: uge_master


#export OS_COMPUTE_API_VERSION=1.1
#token='ZK82GDF1K1J6RLGNXDVU'
#export OS_TENANT_ID='andmalc-project1'
