# Prerequisites: just, git
# Just: if not in pkg manager (Deb Bookworm)
# 	curl -L https://just.systems/install.sh > /install-just.sh
# 	chmod + install-just.sh
#	./install-just.sh # Install just to ~/bin unless --to <path> is given

# ssh setup: download and add id_ed25519 to ~/.ssh from BW
# eval `ssh-agent`
# ssh-add

# Debian: in apt.conf.d file containing APT::Default-Release "/^testing(|-security|-updates)$/";
# Debian: keep bash as login shell. Install directories first then re-login.  Local bin will not be in path until dir is present on login.
# install chezmoi before zellij to avoid replacing the zellij config file

user := env('USER')
#set ignore-comments
#export PATH := env('HOME') + "/.local/bin:" + env('PATH')
#set shell := ["fish", "-c"]

#First setup
#setup: directories dnf-misc fish-config neovim eget chezmoi zellij 

#Add directories {{{1
directories:
	if not test -d ~/.local/bin; mkdir -p ~/.local/bin; end
	if not test -d ~/.local/share; mkdir -p ~/.local/share; end
	if not test -d ~/tmp; mkdir -p ~/tmp; end
	echo "Reboot to update PATH to include local/bin

#First setup
#setup: dnf-misc fish-config neovim eget chezmoi zellij 


#Eget https://github.com/zyedidia/eget {{{1
eget:
	curl https://zyedidia.github.io/eget.sh | sh
	mv eget ~/.local/bin

#Chezmoi {{{1
chezmoi:
	eget twpayne/chezmoi --to ~/.local/bin/chezmoi
	chezmoi init git@github.com:andmalc/dotfiles.git
	chezmoi apply .config/fish/config.fish

# Zellij {{{1
zellij:
	eget --upgrade-only --to ~/.local/bin/zellij zellij-org/zellij

#Fedora console apps {{{1
dnf-misc:
	sudo dnf install -y fish micro ugrep fd-find wget duf mosh bat fzf kitty-terminfo tldr yank wcurl

# Debian console apps {{{1
apt-misc:
        sudo apt --no-install-recommends install -y neovim micro ugrep ripgrep fd-find wget duf mosh bat fzf kitty-terminfo yank tealdeer

#Fish config and Fisher plugin manager {{{1
fisher:
	#!/usr/bin/fish
	#Fisher install to ~/.config/fish/functions
	curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
	fisher update

	#Fish plugins additional
	#fish_fisher_additional:
	#fish-fastdir
	#https://github.com/danhper/fish-fastdir
	#	fisher install tuvistavie/fish-fastdir
fish-config:
	# Change shell to fish
	sudo chsh -s /usr/bin/fish "{{user}}"
	# Just completions
	just --completions fish > ~/.config/fish/completions/just.fish

#Neovim {{{1
neovim:
	sudo dnf install --setopt install_weak_deps=False neovim python3-neovim
	#Nvim-Plug
	# requires git
	sh -c "curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# Micro {{{1
micro:
	eget zyedidia/micro --upgrade-only --to ~/.local/bin/ 

#Less Used {{{1
# Broot file browser {{{2
broot:
	sudo dnf copr enable -y petersen/broot
	sudo dnf update -y
	sudo dnf install -y broot


# Bitwarden Appimage {{{2
bitwarden:
	#Desktop file and icon png should be in ~/.local/share/application via chezmoi
	wget -O ~/.local/bin/bitwarden.appimage https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=appimage

# Batextras {{{2
bat extras:
	sudo dnf install dnf-plugins-core 
	sudo dnf copr enable awood/bat-extras
	sudo dnf install bat-extras
#Eza - ls alternative {{{2
eza:
	eget twpayne/chezmoi

#To Do {{{1

##Atuin shell and desktop {{{2
# https://docs.atuin.sh/guide/installation
# Install with shell plugins for fish and nushell

# vim: fdm=marker ft=make